[workspace]
members = [
    "crates/api",
    "crates/lib",

    "crates/examples/bot"
]

[workspace.package]
authors = ["Yuuki Rika"]
license = "MIT OR Apache-2.0"
description = "Rust typings for the Revolt API."
repository = "https://github.com/yvvki/revolute"
